# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Yogesh Drall'
tagline:          'Personal Blog'
description:      'Software engineer, ❤️(loves) to build high scale products.'
url:              https://www.yogeshdrall.in
baseurl:          '/'

author:
  name:           'Yogesh Drall'
  url:            https://www.yogeshdrall.in

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ydrall/ydrall.github.io


plugins: [jekyll-paginate]
