# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Yogesh Drall'
tagline:          'My Personal Blog'
description:      'I am a fullstack developer. This blog is about programming, technology, gadgets and some random technical stuffs.'
url:              http://ydrall.ml
baseurl:          /

author:
  name:           'Yogesh Drall'
  url:            https://twitter.com/yogeshdrall

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ydrall/ydrall.github.io