# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               ydrall
tagline:             'an experimental branch'
description:         'About Java, Android, Design patterns and some other random stuff.'
url:                 'https://drall.me'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yogesh Drall
  url:               https://www.drall.me
  email:             yogesh@drall.me

# Custom vars
version:             1.0.0

gems:
  - jekyll-paginate
  - jekyll-gist
