# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Blog
# tagline:             'My personal blog'
description:         'About Java, Android, Design patterns and other stuffs i build.'
url:                 http://ydrall.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yogesh Drall
  url:               https://twitter.com/yogesh_drall
  email:             drall.rw@gmail.com

# Custom vars
version:             1.0.0

gems:
  - jekyll-paginate
  - jekyll-gist
